name: C++ CI

on:
  pull_request:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          clang clang-tidy clang-format clang-tools \
          cmake gcc g++ \
          libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev \
          libasio-dev

    - name: Create build directory
      run: mkdir -p build

    - name: Configure project
      run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -B build -S .

    - name: Build project
      run: cmake --build build -- -j4

    - name: Copy compile_commands.json
      run: cp build/compile_commands.json .

    - name: Run clang-format check
      run: ./scripts/format-check.sh

    - name: Run clang-tidy check
      run: ./scripts/tidy-check.sh
