name: C++ CI

on:
  pull_request:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache Conan packages
      uses: actions/cache@v3
      with:
        path: ~/.conan2
        key: conan-${{ runner.os }}-${{ hashFiles('conanfile.txt', 'conan_profile_ci') }}
        restore-keys: |
          conan-${{ runner.os }}-

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          clang clang-tidy clang-format clang-tools \
          cmake gcc g++ \
          python3 python3-pip

    - name: Install Conan
      run: |
        pip3 install conan
        conan profile detect --force

    - name: Install dependencies with Conan
      run: |
        conan install . --output-folder=build --build=missing --profile=conan_profile_ci

    - name: Configure project
      run: cmake --preset conan-release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Build project
      run: cmake --build build -- -j4

    - name: Copy compile_commands.json
      run: cp build/compile_commands.json .

    - name: Run clang-format check
      run: ./scripts/format-check.sh

    - name: Run clang-tidy check
      run: ./scripts/tidy-check.sh
